name: Setup Linux

inputs:
  env:
    required: True

runs:
  using: "composite"
  steps:
    - name: Install Ccache
      shell: bash
      run: |
        # Install ccache with Homebrew
        brew install ccache

        # Add ccache to PATH
        echo 'export PATH="/usr/lib/ccache:$PATH"' >> $GITHUB_PATH

    - name: Install Simple Comic Translator
      shell: bash
      run: |
        # Check Python version
        python --version

        # Create virtual environment
        python -m venv venv

        # Activate it
        source venv/bin/activate

        # Install dependencies
        pip install -r requirements-lock.txt

    - name: Run Simple Comic Translator
      env:
          API_KEYS: ${{ inputs.env }}
      shell: bash
      run: |
        # Activate venv
        source venv/bin/activate

        # Run the app
        python main.py --input "test/remote/manhwa/RAW"