name: Setup Windows

inputs:
  env:
    required: True

runs:
  using: "composite"
  steps:
    - name: Modify variables for testing
      shell: powershell
      run: |
        # Disable Clear-HostLine in downloader.psm1
        $downloaderPath = ".\app\extra\downloader.psm1"
        $oldString = 'Clear-HostLine \$Line'
        $newString = '# Clear-HostLine $Line'

        (Get-Content -Path $downloaderPath -Raw) -replace $oldString, $newString | Set-Content -Path $downloaderPath

        # Replace folder selection with plain path string
        $filePath = ".\launcher.ps1"
        $findPattern = '\$InputPath = Select-FolderDialog'
        $replaceText = '$InputPath = ".\test\remote\manhwa\RAW"'

        (Get-Content -Path $filePath -Raw) -replace $findPattern, $replaceText | Set-Content -Path $filePath

        # Replace the use of .env file with GitHub Secrets
        $filePath = ".\app\core\translation.py"
        $findPattern = 'api_key=api_key'
        $replaceText = ''

        (Get-Content -Path $filePath -Raw) -replace $findPattern, $replaceText | Set-Content -Path $filePath

    - name: Run installer.ps1
      shell: powershell
      run: |
        # Change Execution Policy for Pyenv Windows
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine

        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        Write-Host "$(where.exe python)`n"

        # Run the installer
        .\installer.ps1

        $ErrorLogPath = ".\Temp\log_errors-install.txt"

        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run launcher.ps1
      env:
          GEMINI_API_KEY: ${{ inputs.env }}
      shell: powershell
      run: |
        # Set the system locale to use UTF-8 (Codepage 65001)
        $process = Start-Process -FilePath "powershell" -ArgumentList "Set-WinSystemLocale -Locale 'en-US' -GeoId 244; `
          $psversiontable.psversion.major; `
          [Console]::OutputEncoding; `
          [Console]::InputEncoding;" -Verb RunAs -PassThru -WindowStyle Hidden
        $process | Wait-Process

        # Verify the change in the current process
        chcp 65001
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::InputEncoding = [System.Text.Encoding]::UTF8

        # Run the launcher
        $ErrorLogPath = ".\Temp\log_errors-launcher.txt"

        .\launcher.ps1 > $ErrorLogPath
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run updater.ps1
      shell: powershell
      run: |
        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        # Run the updater
        .\updater.ps1 | Out-String -Stream | Write-Host > $ErrorLogPath

        $ErrorLogPath = ".\Temp\log_errors-updater.txt"
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }